(() => {
 'use strict';
 const $=id=>document.getElementById(id),forms=window.RinkouForms,dialog=$('evolutionDialog'),canvas=$('evolutionCanvas'),c=canvas.getContext('2d'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 let route='spread',power=0,animation=null,last=0,time=0,scroll=0;
 function update(){const d=forms.describe(route,power);dialog.style.setProperty('--accent',forms.COLORS[route]);$('evolutionVersion').textContent=route.toUpperCase()+' '+forms.STEPS[power].version;$('evolutionName').textContent=d.name;$('evolutionShape').textContent=d.shape;$('evolutionAttack').textContent=d.attack;$('evolutionMusic').textContent=d.music+' · 背景速度 '+(forms.STEPS[power].travelSpeed/forms.STEPS[0].travelSpeed).toFixed(1)+'×';$('previewSpread').setAttribute('aria-pressed',String(route==='spread'));$('previewLaser').setAttribute('aria-pressed',String(route==='laser'));document.querySelectorAll('#evolutionSteps button').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.power)===power)));canvas.setAttribute('aria-label',`${route.toUpperCase()} ${forms.STEPS[power].version}、${d.name}。${d.shape}`);}
 function stroke(x,y,x2,y2,col,width,blur){c.beginPath();c.moveTo(x,y);c.lineTo(x2,y2);c.lineWidth=width;c.strokeStyle=col;c.shadowColor=col;c.shadowBlur=blur;c.stroke();}
 function frame(now){if(!dialog.open){animation=null;return;}const dt=last?Math.min(.04,(now-last)/1000):0;last=now;if(!reduced){time+=dt;scroll+=dt*forms.STEPS[power].travelSpeed;}const cw=canvas.clientWidth||760,ch=canvas.clientHeight||280,ratio=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(cw*ratio)||canvas.height!==Math.round(ch*ratio)){canvas.width=Math.round(cw*ratio);canvas.height=Math.round(ch*ratio);}c.setTransform(ratio,0,0,ratio,0,0);const k=Math.min(1.45,(cw-40)/360,(ch-24)/196),x=cw/2,y=ch*.43,col=forms.COLORS[route];c.clearRect(0,0,cw,ch);c.fillStyle='#030c13';c.fillRect(0,0,cw,ch);const g=c.createRadialGradient(x,y,10,x,y,250);g.addColorStop(0,col+'19');g.addColorStop(1,col+'00');c.fillStyle=g;c.fillRect(0,0,cw,ch);c.strokeStyle=col+'18';c.lineWidth=1;c.shadowBlur=0;for(let i=0;i<cw;i+=38){c.beginPath();c.moveTo(i,0);c.lineTo(i,ch);c.stroke();}for(let i=scroll%35;i<ch;i+=35){c.beginPath();c.moveTo(0,i);c.lineTo(cw,i);c.stroke();}
  c.fillStyle=col+'88';for(let i=0;i<46;i++){const depth=.4+(i%7)*.2,px=((i*137)%997)/997*cw,py=(((i*53)%401)/401*ch+scroll*depth)%ch;c.fillRect(px,py,1,1+(reduced?0:forms.STEPS[power].travelSpeed*.04*depth));}
  c.save();c.globalCompositeOperation='lighter';
  if(route==='spread')for(const p of forms.spreadMuzzles(power,reduced?0:time))for(let j=0;j<4;j++){const travel=((time*240+j*75)%300);const px=x+p.x*k+Math.cos(p.angle)*travel,py=y+p.y*k+Math.sin(p.angle)*travel;stroke(px,py,px-Math.cos(p.angle)*13,py-Math.sin(p.angle)*13,col,3.2,8);}
  else for(const p of forms.laserBeams(power,reduced?0:time)){stroke(x+p.x*k,y+p.y*k,x+p.x*k,-5,col,p.width*.7,13);stroke(x+p.x*k,y+p.y*k,x+p.x*k,-5,'#eefaff',Math.max(1,p.width*.15),3);}
  c.restore();forms.draw(c,{route,power,time,x,y,scale:k,reduced});c.shadowBlur=0;animation=requestAnimationFrame(frame);
 }
 $('evolutionButton').addEventListener('click',()=>{route=document.querySelector('input[name="route"]:checked')?.value||'spread';power=0;update();dialog.showModal();last=0;time=0;scroll=0;if(animation===null)animation=requestAnimationFrame(frame);});
 $('evolutionClose').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{if(animation!==null)cancelAnimationFrame(animation);animation=null;$('evolutionButton').focus();});
 $('previewSpread').addEventListener('click',()=>{route='spread';update();});$('previewLaser').addEventListener('click',()=>{route='laser';update();});
 document.querySelectorAll('#evolutionSteps button').forEach(b=>b.addEventListener('click',()=>{power=Number(b.dataset.power);update();}));
})();
